//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BJScore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BJScore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ace {
            get {
                object obj = ResourceManager.GetObject("Ace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eight {
            get {
                object obj = ResourceManager.GetObject("Eight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Five {
            get {
                object obj = ResourceManager.GetObject("Five", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Four {
            get {
                object obj = ResourceManager.GetObject("Four", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jack {
            get {
                object obj = ResourceManager.GetObject("Jack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap King {
            get {
                object obj = ResourceManager.GetObject("King", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nine {
            get {
                object obj = ResourceManager.GetObject("Nine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Queen {
            get {
                object obj = ResourceManager.GetObject("Queen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seven {
            get {
                object obj = ResourceManager.GetObject("Seven", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Six {
            get {
                object obj = ResourceManager.GetObject("Six", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap strategy {
            get {
                object obj = ResourceManager.GetObject("strategy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 2 9 2	
        ///1 12 2 2
        ///1 2 11 2
        ///1 2 10 2
        ///1 3 7 1 
        ///1 4 5 3 
        ///1 3 5 3 
        ///1 2 4 1 
        ///1 0 1 1 
        ///1 0 2 1 
        ///1 0 3 1 
        ///1 0 5 1 
        ///1 0 6 1 
        ///1 6 6 4
        ///1 5 5 4 
        ///1 2 2 4 
        ///1 1 1 4
        ///2 3 9 2
        ///2 10 3 2 
        ///2 11 3 2 
        ///2 3 12 2
        ///2 2 9 2 
        ///2 11 2 2
        ///2 1 9 1 
        ///2 10 1 1
        ///2 2 5 3 
        ///2 1 5 1 
        ///2 0 6 3
        ///2 0 5 3
        ///2 0 4 1 
        ///2 0 3 1 
        ///2 0 2 1 
        ///2 7 7 4
        ///2 4 4 3 
        ///2 3 3 1
        ///2 1 1 4
        ///3 3 9 2
        ///3 10 3 2 
        ///3 12 3 2  
        ///3 2 9 2 
        ///3 2 10 2 
        ///3 2 11 2
        ///3 1 9 2 
        ///3 1 12 2
        ///3 11 1 2
        ///3 3 5 3 
        ///3 2 4 1 
        ///3 0 6 3 
        ///3 0 5 3 
        ///3 0 4 3 
        ///3 0 3 3 
        ///3 0 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrategyScenarios {
            get {
                return ResourceManager.GetString("StrategyScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ten {
            get {
                object obj = ResourceManager.GetObject("Ten", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 2 9 2
        ///1 3 7 1
        ///1 4 5 3
        ///1 3 5 3
        ///1 0 1 1
        ///1 0 2 1.
        /// </summary>
        internal static string TestImports {
            get {
                return ResourceManager.GetString("TestImports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Three {
            get {
                object obj = ResourceManager.GetObject("Three", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Two {
            get {
                object obj = ResourceManager.GetObject("Two", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
